services:
  frontend:
    build: 
      context: ./frontend  # Specify frontend directory
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app  # Mount only frontend folder
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./backend  # Specify backend directory
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app  # Mount only backend folder
    ports:
      - "5000:5000"
